# This file was generated by GoReleaser. DO NOT EDIT.
cask "focal" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "bf4539483e140dc013ca43bd158743088fdb656ab523e871540e20001e1f96e5"
      url "https://github.com/victoraldir/focal/releases/download/v#{version}/focal_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7673543927c75a0936160c16f1a461d1ea54a1cc66b150a37b137864ee476f22"
      url "https://github.com/victoraldir/focal/releases/download/v#{version}/focal_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "focal"
  desc "Convert photo sequences into timelapses by wrapping FFmpeg"
  homepage "https://github.com/victoraldir/focal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "focal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/focal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    focal wraps FFmpeg. If ffmpeg is not already on your PATH, focal downloads
    a static build into ~/Library/Caches/focal/bin on first use.
  EOS
end
