# This file was generated by GoReleaser. DO NOT EDIT.
cask "focal" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "814d6328a83d408b2e88ee72092e02880b6f4c6f53deb0a746cc83a98c469364"
      url "https://github.com/victoraldir/focal/releases/download/v#{version}/focal_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff9ad9630419d5d35e421eef364947a647efcc1552823d346b3cbc0a913b14b1"
      url "https://github.com/victoraldir/focal/releases/download/v#{version}/focal_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "focal"
  desc "Convert photo sequences into timelapses by wrapping FFmpeg"
  homepage "https://github.com/victoraldir/focal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "focal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/focal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    focal wraps FFmpeg. If ffmpeg is not already on your PATH, focal downloads
    a static build into ~/Library/Caches/focal/bin on first use.
  EOS
end
